import { StyleSheet } from 'react-native'

export const ListingStyle = (StyleSheet.createstyle = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff',
        paddingTop: '10%',
        fontFamily: 'Baloo',
    },
    // loader: {
    //     width: '1O0%',
    //     display: 'flex',
    //     justifyContent: 'center',
    //     alignItems: 'center',
    // },
    image: {
        height: 250,
        width: '100%',
    },
    card: {
        position: 'relative',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginTop: 34,
        width: '100%',
        height: '30%',
        marginBottom: 60,
    },
    rightButton: {
        width: 40,
        height: 40,
        right: 25,
        top: '50%',
        position: 'absolute',
        backgroundColor: '#A1A8B9',
        borderRadius: 99,
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        opacity: 0.3,
    },
    leftButton: {
        width: 40,
        height: 40,
        left: 25,
        top: '50%',
        position: 'absolute',
        backgroundColor: '#A1A8B9',
        borderRadius: 99,
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        opacity: 0.3,
    },
    chevron: {
        width: 20,
        height: 20,
        opacity: 1,
    },
    cardContainer: {
        width: '100%',
    },
    data: {
        height: '42%',
        paddingTop: 20,
    },

    categoryInfo: {
        borderRadius: 9,
        borderColor: '#91C788',
        marginRight: 8,
        color: '#91C788',
        paddingHorizontal: 8,
        paddingVertical: 8,
        backgroundColor: 'black',
    },
    cardDatas: {
        height: 80,
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 20,
    },
    flex: {
        display: 'flex',
        alignItems: 'center',
        fontSize: 12,
        flexDirection: 'row',
        marginBottom: 20,
    },

    infoUser: {
        fontSize: 12,
    },
    category: {
        width: '25%',
        color: '#91C788',
        padding: 3,
        borderColor: '#91C788',
        borderWidth: 2,
        borderRadius: 12,
        textAlign: 'center',
        marginRight: 10,
    },
    categories: {
        display: 'flex',
        flexDirection: 'row',
        paddingLeft: 25,
    },
    title: {
        fontSize: 20,
        marginTop: 21,
        paddingLeft: 25,
        fontWeight: 'bold',
        color: '#495566',
    },
    contactButton: {
        backgroundColor: '#91C788',
        paddingVertical: 5,
        borderRadius: 99,
        height: 30,
        width: 90,
        marginBottom: 20,
    },
    contactButtonText: { color: '#ffffff', textAlign: 'center' },
    locationData: {
        display: 'flex',
        alignItems: 'center',
        flexDirection: 'row',
        paddingHorizontal: 16,
        justifyContent: 'space-between',
        height: 40,
        width: '60%',
        paddingLeft: 25,
        marginBottom: 10,
    },
    grayDark: {
        color: '#495566',
    },
    description: {
        height: '30%',
        paddingLeft: 25,
    },

    label: {
        fontSize: 16,
        marginBottom: 5,
        fontWeight: 'bold',
        color: '#495566',
    },
    userName: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#495566',
    },

    avatarPic: {
        width: 35,
        height: 35,
        borderRadius: 99,
        marginHorizontal: 5,
    },
}))
