import { StyleSheet } from 'react-native'

export const FiltersMenuStyle = (StyleSheet.createstyle = StyleSheet.create({
    secondMenu: {
        backgroundColor: '#E5E5E5',
        height: 60,
        marginBottom: '10%',
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-around',
        paddingVertical: '5%',
        alignItems: 'center',
    },
    offersButton: {
        backgroundColor: '#91C788',
        color: '#fff',
        textAlign: 'center',
        width: 85,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#91C788',
        height: 30,
        marginHorizontal: 3,
    },
    ordersButton: {
        color: '#91C788',
        backgroundColor: '#fff',
        textAlign: 'center',
        width: 85,
        height: 30,
        marginHorizontal: 3,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#91C788',
    },
    filtersButton: {
        width: 120,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#6A6F7D',
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-around',
    },
    secondMenuProductButtons: {
        width: '40%',
        display: 'flex',
        justifyContent: 'space-between',
        flexDirection: 'row',
    },
    offersButtonText: {
        color: '#fff',
        textAlign: 'center',
        width: '100%',
        height: 30,
        fontSize: 10,
        textAlignVertical: 'center',
        paddingVertical: 7,
        textTransform: 'uppercase',
        fontWeight: 'bold',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#91C788',
    },
    ordersButtonText: {
        color: '#91C788',
        textAlign: 'center',
        width: '100%',
        height: 30,
        fontSize: 10,
        paddingVertical: 7,
        borderRadius: 12,
        borderWidth: 0.5,
        borderColor: '#C5C6CC',
        textTransform: 'uppercase',
        fontWeight: 'bold',
    },
    filtersButtonText: {
        backgroundColor: 'transparent',
        color: '#000',
        textAlign: 'center',
        height: 30,
        marginHorizontal: 'auto',
        fontSize: 10,
        textTransform: 'uppercase',
        fontWeight: 'bold',
        paddingVertical: 7,
    },
    filterIcon: {
        width: 25,
        height: 25,
        marginLeft: 5,
        marginTop: 4,
    },
    notificationFilter: {
        width: 20,
        height: 20,
        backgroundColor: '#91C788',
        borderRadius: 999,
        marginTop: 4,
    },
    notificationText: {
        color: 'white',
        textAlign: 'center',
        fontWeight: 'bold',
        fontSize: 10,
        paddingVertical: 4,
    },
}))
